### ISSUE TITLE
Yarn error again

### ISSUE THREAD

**Issue by retard-sonn** [Ferks-FK/Pterodactyl-AutoAddons#14]
```
ERROR in resources/scripts/components/server/files/FileViewer.tsx:54:60
TS2322: Type '{ details: boolean; key: string; file: FileObject; }' is not assignable to type 'IntrinsicAttributes & { file: FileObject; }'.
  Property 'details' does not exist on type 'IntrinsicAttributes & { file: FileObject; }'.
    52 |                                     {
    53 |                                         sortFiles(files.slice(0, maxFiles)).map(file => (
  > 54 |                                             <FileObjectRow details={details} key={file.key} file={file}/>
       |                                                            ^^^^^^^
    55 |                                         ))
    56 |                                     }
    57 |                                     <MassActionsBar/>
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Got this error again when installing addon 3 on panel 1.7.0

**Comment by Ferks-FK** [comment]
> ```
> ERROR in resources/scripts/components/server/files/FileViewer.tsx:54:60
> TS2322: Type '{ details: boolean; key: string; file: FileObject; }' is not assignable to type 'IntrinsicAttributes & { file: FileObject; }'.
>   Property 'details' does not exist on type 'IntrinsicAttributes & { file: FileObject; }'.
>     52 |                                     {
>     53 |                                         sortFiles(files.slice(0, maxFiles)).map(file => (
>   > 54 |                                             <FileObjectRow details={details} key={file.key} file={file}/>
>        |                                                            ^^^^^^^
>     55 |                                         ))
>     56 |                                     }
>     57 |                                     <MassActionsBar/>
> error Command failed with exit code 2.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```
> 
> Got this error again when installing addon 3 on panel 1.7.0

This error has a solution in the discord support group in the fixed messages.
Please stop opening issues here and use the support group.
