### ISSUE TITLE
[Addon] Mysql

### ISSUE THREAD

**Issue by Anas-1554** [Ferks-FK/Pterodactyl-AutoAddons#2]
MySQL import and export addon which can backup MySQL in .sql and save it in server file manager

**Comment by Anas-1554** [comment]
![Screenshot 2021-12-29 205824](https://user-images.githubusercontent.com/94738878/147677806-8f02e61f-5f4c-4cdd-ad72-9eb807edfe0b.png)
Here is a demo

**Comment by Ferks-FK** [comment]
This does not seem to be something simple to do, I am not experienced with TypeScript to create this.
I'll leave it to another dev :)
