### ISSUE TITLE
Update ReadMe to say "Addons" instead of "Themes"

### ISSUE THREAD

**Issue by DarkShoro** [Ferks-FK/Pterodactyl-AutoAddons#7]
In the last section of the ReadMe file, you can read:

Extra informations
If you have a **theme**, and would like to add it to the script, feel free to suggest it in the support group.

Can you change it to say addons ? I think it's just due to a copy/paste from the AutoTheme Readme

**Comment by Ferks-FK** [comment]
> In the last section of the ReadMe file, you can read:
> 
> Extra informations If you have a **theme**, and would like to add it to the script, feel free to suggest it in the support group.
> 
> Can you change it to say addons ? I think it's just due to a copy/paste from the AutoTheme Readme

Yes, you are right, thanks 🤠
